services:
  server:
    build:
      context: .
    volumes:
      - ssh-php-ssh:/home/server/.ssh
    ports:
      - 2201:22 # Change to 22:22 if you don't have an SSH server running already
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
volumes:
  ssh-php-ssh:
